### ISSUE TITLE
Should we update id by setting it equal to provided one + 1?

### ISSUE THREAD

**Issue by kirushyk** [dpskvn/express-sse#10]
https://github.com/dpskvn/express-sse/blob/master/index.js#L50

**Comment by dpskvn** [comment]
No because the provided ID could be a string (a hash of some kind or a random string) which'll make it impossible to auto-increment it. 

Custom IDs make it possible to manage them externally, but I think we should keep the internal mechanism simple and independent. 

Does that make sense?

**Comment by kirushyk** [comment]
Yup, I didn't know standard allows string IDs.
