### ISSUE TITLE
warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit. Trace

### ISSUE THREAD

**Issue by ghdna** [dpskvn/express-sse#15]
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at SSE.addListener (events.js:252:17)
    at SSE.init

**Comment by dpskvn** [comment]
What version of `express-sse` are you using?

**Comment by ghdna** [comment]
0.3.2

**Comment by dpskvn** [comment]
Please try running `npm update express-sse`, that issue should be fixed in 0.4.0.

Let me know if that fixes it.

**Comment by ghdna** [comment]
The error doesn't show up in 0.4.0 any more. But after 5-6 requests, the page becomes unresponsive and I need to close the browser and open new window. Should I be closing the events explicitly in my server.js?

**Comment by dpskvn** [comment]
No, they should close on their own. Hmm... Can you share your code/use case? I'm having a hard time replicating the error.

**Comment by ghdna** [comment]
Ok, give me few hours. Skype would work as well.
