### ISSUE TITLE
Conflict with compression

### ISSUE THREAD

**Issue by Kefir100** [dpskvn/express-sse#26]
Hey! Found out the module is incomptaible with express [compression middleware](https://github.com/expressjs/compression). It causes an interesting bug. No matter what I do, the initial event is not sent to the clinet, and each event on a client is one event late from the server sent event.

Though the fix is pretty easy - it needs to have a [res.flush()](https://github.com/expressjs/compression#server-sent-events). It would be real nice for the package to be compatible with compression.

Thanks!

**Comment by dpskvn** [comment]
Thank you!
