### ISSUE TITLE
How do you actually run this?

### ISSUE THREAD

**Issue by MichaelXavier** [dpskvn/express-sse#9]
Hi!

I'm using this on node 4.6.0. I'm not a node developer and am just trying to prop up a simple SSE demo. It seems like the source of this is is using some ES6 features. If I run example code with `node server.js` I'll see:

```
class SSE extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

So if I run it with `node --use_strict` I get 

```
constructor(initial = []) {
                      ^

SyntaxError: Unexpected token =
```

Are you guys running on some kind of bleeding edge version of node? Are there other flags I need to be passing?

**Comment by dpskvn** [comment]
Set up an [express](https://github.com/expressjs/express) project, `npm install express-sse` and follow the readme.

**Comment by MichaelXavier** [comment]
I got it to work with node 6.8.1. Is Node 6 the minimum version supported?

**Comment by dpskvn** [comment]
Hmm, 4 should've been supported, too. I'll have to rectify that in the next release.

**Comment by dpskvn** [comment]
Alright, node v4 compatibility restored in 0289846fb01c325286f1d532e9654ebb94be7e78
